version: "3.8"

services:
#  app:
#    build: .
#    restart: always
#    container_name: golang-app
#    ports:
#      - "5050:5050"
#    environment:
#      PORT: 5050
#      JWT_SECRET: "5Jet8Tmduugq8eMV9nX7o0DVCLbWIi5UOvL2LfiMEJz1LPF3uqLXjjAuXiuobBhfvaUhV4G3VlW7cUESmuxT7p6Gi8IMSOt3A2nYgJiHo9B8D_vCXADHZw9C2OlsTF-YB-o70i3UqFgzyQl9Y4ImMZuUCB0YR-QxB5rU7jFfbK9_7sDIaj0WtbXv_esSySoUqn1YbyRQGK9SwvnaeC3MoRSiffYULvIaJxncFQ-fsuna-L7ESVAfmqpp87cYTsTK_7Sk07_8R3BLTiOz6Qvt-jL6y_EAZtHowMtSNn-2O7HVqQ699xpt04dzSrvRhq65Rfz5Tn4TOB_pkXvxinXQPw"
#      DATABASE_URL: "host=db:5432 user=root password=root dbname=pgdb sslmode=disable"
#      ENVIRONMENT: Local
#    depends_on:
#      - db
  db:
    image: postgres
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pgdb
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
  nats:
    image: nats-streaming
    container_name: nats
    restart: always
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    environment:
      - "discover.type=single-node"