version: "3"
services:
    db:
        image: mysql:8.0
        restart: always
        ports:
            - 3307:3306
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=userpass
        volumes:
            - ./mysql:/var/lib/mysql # persistent database data.
            - ./db-scripts:/docker-entrypoint-initdb.d #scripts