version: "3"
services:
    db:
        image: postgres
        restart: always
        container_name: database
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: platzi-market
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./database-data/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
            - ./database-data/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
            PGADMIN_LISTEN_PORT: "80"
        ports:
            - "5050:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
            
            
volumes:
    db-data:
    pgadmin-data: